- job:
    name: ironic-ui-integration-tests
    parent: horizon-integration-tests
    required-projects:
      - name: openstack/horizon
      - name: openstack/ironic
      - name: openstack/python-ironicclient
      - name: openstack/ironic-ui
    roles:
      - zuul: openstack-infra/devstack
      - zuul: openstack/horizon
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$
    vars:
      devstack_plugins:
        ironic: https://opendev.org/openstack/ironic
        ironic-ui: https://opendev.org/openstack/ironic-ui
      devstack_services:
        horizon: true
      tox_envlist: integration

- project:
    templates:
      - check-requirements
      - horizon-nodejs10-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python3-train-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - ironic-ui-integration-tests:
            voting: false
