- project:
    templates:
      - check-requirements
      - openstack-python-jobs
      - openstack-python35-jobs
      - nodejs4-jobs
      - publish-openstack-sphinx-docs
      - release-notes-jobs
